"""fix lead model

Revision ID: 0a2636636ed6
Revises: f570cb71a7e3
Create Date: 2025-10-31 17:31:06.839527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a2636636ed6'
down_revision: Union[str, Sequence[str], None] = 'f570cb71a7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('found_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('leads', 'source_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('leads', 'found_date')
    op.alter_column('transactions', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('transactions', 'type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=15, scale=6),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=mysql.DECIMAL(precision=15, scale=6),
               nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('transactions', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.add_column('leads', sa.Column('found_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('leads', 'source_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('leads', 'found_at')
    op.drop_column('leads', 'first_name')
    op.drop_column('leads', 'username')
    # ### end Alembic commands ###
